import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/header"
import { ReactNode } from "react"   // ✅ import ReactNode

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1 container mx-auto p-6">{children}</main>
          {/* contents from ./page.tsx */}
          <footer className="border-t bg-white p-4 text-center text-sm text-gray-500">
            © 2025 My To-Do App
          </footer>
        </div>
      </body>
    </html>
  )
}
